import React, { useEffect, useState } from 'react';
import { useParams, Link, Navigate, useLocation } from 'react-router-dom';
import { Helmet } from 'react-helmet-async';
import { Calendar, User, ArrowLeft, Share2, ExternalLink, Brain } from 'lucide-react';
import AdWrapper from '../components/AdWrapper';

const articlesContent: Record<string, { title: string; date: string; author: string; content: string[] }> = {
  'caitlin-clark-2026-season-preview': {
    title: 'Caitlin Clark 2026 Season Preview: Elevating the Indiana Fever',
    date: 'May 20, 2026',
    author: 'Fever Game Analytics Team',
    content: [
      "The 2026 WNBA season has arrived, and all eyes are once again on the Indiana Fever and their generational point guard, Caitlin Clark. After a historic rookie campaign that shattered viewership records and redefined offensive spacing, the expectations have only grown. This season preview breaks down what fans can expect from Clark and the Fever as they aim for championship contention.",
      "Caitlin Clark's impact goes far beyond her signature logo threes. Last season, she established herself as one of the premier playmakers in the league. Opposing defenses often sold out to stop her perimeter shooting, allowing her to exploit the pick-and-roll and find her teammates with pinpoint precision. Heading into 2026, the chemistry between Clark and the rest of the Fever core has visibly matured.",
      "One of the biggest storylines to follow is Clark's physical development and defensive positioning. The Fever's coaching staff emphasized defensive schemes during the offseason, ensuring that Clark can effectively navigate screens and close out on shooters without expending excessive energy. If the preseason is any indicator, Clark has added noticeable upper-body strength, allowing her to absorb contact better on drives to the basket.",
      "Furthermore, the transition offense of the Indiana Fever looks terrifying. When Clark grabs a defensive rebound or receives an outlet pass, she transforms the court into a track meet. Her ability to throw accurate full-court passes forces defenses to sprint back immediately, often leading to easy transition layups or wide-open trailing three-pointers.",
      "Ultimately, the 2026 season for Caitlin Clark isn't just about individual accolades; it's about translating those statistical achievements into deep playoff success. If the supporting cast can consistently knock down the open looks generated by Clark's gravity, the Fever have a legitimate path to the WNBA Finals. The basketball world is watching, and Caitlin Clark is ready to deliver."
    ]
  },
  'fever-playoff-push': {
    title: 'Indiana Fever Playoff Push: The Road Ahead',
    date: 'May 15, 2026',
    author: 'Fever Game Analytics Team',
    content: [
      "As the regular season hits its crucial midpoint, the Indiana Fever find themselves in the thick of the playoff race. The atmosphere inside Gainbridge Fieldhouse is electric, driven by a passionate fanbase that believes this young, dynamic roster is destined for greatness. But the road to securing a top playoff seed in the highly competitive WNBA is never easy.",
      "The key to the Fever's recent success has been their balanced offensive attack. While Caitlin Clark naturally commands the spotlight, it is the emergence of secondary scorers that makes this team so dangerous. When defenses trap or blitz Clark, players like Kelsey Mitchell and Aliyah Boston have consistently made them pay. Boston's interior dominance provides a vital anchor, forcing opponents to respect the paint and preventing them from strictly guarding the perimeter.",
      "Defensively, the Fever have made significant strides compared to last season. They are communicating better on switches and showing more resilience in late-game situations. However, to truly solidify their position as title contenders, they must improve their defensive rebounding percentage. Too often, opposing teams have gained extra possessions through offensive boards, leading to momentum-shifting second-chance points.",
      "Looking at the upcoming schedule, the Fever face a grueling stretch of road games against championship-caliber opponents like the Las Vegas Aces and the New York Liberty. These matchups will serve as the ultimate litmus test. Winning on the road requires a level of mental toughness and execution that the Fever's young core must demonstrate they possess.",
      "If the Indiana Fever can navigate this difficult stretch and secure home-court advantage for the first round, they will be an incredibly tough out in a series. The combination of elite perimeter shooting, dominant interior play, and a raucous home crowd makes them a nightmare matchup for any team in the league."
    ]
  },
  'breaking-down-the-pick-and-roll': {
    title: 'Tactical Breakdown: The Clark-Boston Pick and Roll',
    date: 'May 10, 2026',
    author: 'Fever Game Analytics Team',
    content: [
      "In modern basketball, the pick-and-roll (PnR) is the foundational building block of half-court offense. For the Indiana Fever, the combination of Caitlin Clark and Aliyah Boston executing the PnR has become one of the most devastating and unguardable actions in the WNBA. Today, we dive into the game film to analyze why this pairing is so effective.",
      "The fundamental dilemma for opposing defenses lies in the distinct elite skills of both players. Caitlin Clark possesses unlimited shooting range. If a defender chooses to go 'under' the screen set by Boston, Clark will immediately pull up and sink a three-pointer from thirty feet. Therefore, defenders are forced to fight over the top of the screen, naturally putting them trailing the play.",
      "This is where Aliyah Boston's mastery comes into effect. When the defense 'blitzes' or double-teams Clark to prevent the shot, Boston sets a hard, legal screen and then executes a rapid 'short roll' to the free-throw line area. Clark, possessing elite court vision, delivers a crisp pocket pass to Boston. Catching the ball with a 4-on-3 advantage, Boston's decision-making shines.",
      "From the short roll, Boston can either take a high-percentage mid-range jumper, drive powerfully to the rim against a rotating defender, or kick the ball out to a wide-open shooter in the corner if the defense collapses completely. It is a 'pick your poison' scenario for the opponent, and more often than not, the Fever end up with a highly efficient shot attempt.",
      "Head coach Christie Sides has brilliantly diversified the angles and locations where this PnR is initiated—sometimes starting it high at the logo, other times executing it on the empty side of the floor. As Clark and Boston continue to build their telepathic on-court connection, this action will remain the engine of the Indiana Fever's high-octane offense."
    ]
  }
};

const enhanceHeadline = (title: string) => {
  const t = title.toLowerCase();
  let prefix = "Deep Dive | ";
  if (t.includes('clark')) prefix = "Clark Spotlight | ";
  else if (t.includes('boston')) prefix = "Boston Focus | ";
  else if (t.includes('mitchell')) prefix = "Mitchell Focus | ";
  else if (t.includes('playoff') || t.includes('standings')) prefix = "Playoff Race | ";
  else if (t.includes('win') || t.includes('loss') || t.includes('beat') || t.includes('game')) prefix = "Game Analysis | ";
  
  return `${prefix}${title}`;
};

const generateContext = (title: string, description: string) => {
  const t = (title + ' ' + (description || '')).toLowerCase();
  const content = [];
  
  content.push("📊 Fever Tactical Breakdown & Context:");
  
  if (t.includes('clark')) {
    content.push("Caitlin Clark continues to be a focal point for the Indiana Fever and the WNBA at large. Her elite court vision and limitless shooting range frequently force opposing defenses into impossible choices, often heavily impacting the game's outcome even when she isn't the leading scorer.");
  }
  if (t.includes('boston')) {
    content.push("Aliyah Boston remains the crucial anchor in the paint. Her ability to dominate the glass and provide high-efficiency scoring down low provides the necessary balance to the Fever's perimeter-oriented attack.");
  }
  if (t.includes('mitchell')) {
    content.push("Kelsey Mitchell's veteran leadership and dynamic shot-creation are indispensable. She consistently punishes defenses that overcommit, serving as a reliable primary scorer when the offense stagnates.");
  }
  if (t.includes('playoff') || t.includes('standings') || t.includes('seed')) {
    content.push("As the playoff race intensifies, every single possession matters. The Fever's young core is gaining invaluable experience navigating high-pressure situations, which is critical for securing a favorable postseason seed.");
  }
  if (t.includes('coach') || t.includes('sides') || t.includes('defense')) {
    content.push("Coaching adjustments and defensive rotations are under a microscope. Finding the right mix of defensive intensity and offensive spacing is the coaching staff's primary objective as they look to build a consistent winning culture.");
  }
  
  if (content.length === 1) {
    content.push("The Indiana Fever are navigating a highly competitive WNBA landscape. With a blend of emerging superstars and established veterans, the team's trajectory is drawing massive attention from fans and analysts alike. Every game and roster move carries significant implications for their long-term championship aspirations.");
  }

  content.push("Our analytics team suggests that maintaining offensive efficiency and limiting opponents' second-chance points will be the key determining factors in how this specific storyline develops in the coming weeks.");
  
  return content;
};

const NewsArticle = () => {
  const { articleId } = useParams<{ articleId: string }>();
  const location = useLocation();
  const stateArticle = location.state?.article;

  const [article, setArticle] = useState<any>(null);

  useEffect(() => {
    if (stateArticle) {
      // It's a dynamic ESPN article passed via router state
      const extraContext = generateContext(stateArticle.title, stateArticle.description);
      const enhancedTitle = enhanceHeadline(stateArticle.title);
      
      setArticle({
        title: enhancedTitle,
        date: new Date(stateArticle.published).toLocaleDateString('en-US', {
          year: 'numeric', month: 'long', day: 'numeric'
        }),
        author: 'ESPN & Fever Analytics Team',
        content: [
          `📰 ESPN Synopsis: ${stateArticle.description}`,
          ...extraContext
        ],
        imageUrl: stateArticle.imageUrl,
        originalLink: stateArticle.link
      });
    } else if (articleId && articlesContent[articleId]) {
      setArticle(articlesContent[articleId]);
    }
  }, [articleId, stateArticle]);

  if (!article && !stateArticle && !articlesContent[articleId || '']) {
    return <Navigate to="/news" replace />;
  }

  if (!article) return null;

  return (
    <div className="min-h-screen bg-white">
      <Helmet>
        <title>{article.title} | Fever Game Today</title>
        <meta name="description" content={article.content[0].substring(0, 160) + '...'} />
        <link rel="canonical" href={`https://fevergame.space/news/${articleId || ''}`} />
      </Helmet>

      {/* Article Header */}
      <div className="bg-gray-50 py-12 border-b border-gray-200">
        <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8">
          <Link to="/news" className="inline-flex items-center text-red-600 hover:text-red-700 font-medium mb-8 transition-colors">
            <ArrowLeft className="h-4 w-4 mr-2" />
            Back to News
          </Link>
          
          <h1 className="text-3xl md:text-5xl font-black text-gray-900 mb-6 leading-tight">
            {article.title}
          </h1>

          {article.imageUrl && (
            <div className="w-full h-64 sm:h-96 rounded-2xl overflow-hidden mb-8 shadow-md">
              <img src={article.imageUrl} alt={article.title} className="w-full h-full object-cover" />
            </div>
          )}
          
          <div className="flex items-center justify-between border-t border-b border-gray-200 py-4 mt-8">
            <div className="flex flex-wrap items-center gap-4 text-sm text-gray-600">
              <div className="flex items-center font-medium">
                <User className="h-4 w-4 mr-2" />
                {article.author}
              </div>
              <div className="hidden sm:block text-gray-300">|</div>
              <div className="flex items-center">
                <Calendar className="h-4 w-4 mr-2" />
                {article.date}
              </div>
            </div>
            
            <button className="flex items-center text-gray-500 hover:text-red-600 transition-colors">
              <Share2 className="h-5 w-5" />
            </button>
          </div>
        </div>
      </div>

      {/* Article Content */}
      <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
        <AdWrapper scriptSrc="//basionsassay.com/gS5NYpqxJC21IMFEG/144793" />
        <article className="prose prose-lg prose-red max-w-none text-gray-800 mt-8">
          {article.content.map((paragraph: string, idx: number) => {
            const isContextHeader = paragraph.includes('📊 Fever Tactical Breakdown');
            const isESPNSynopsis = paragraph.includes('📰 ESPN Synopsis:');
            
            if (isContextHeader) {
              return <h2 key={idx} className="text-2xl font-black text-blue-700 mt-12 mb-6 border-b-2 border-blue-100 pb-2 flex items-center"><Brain className="w-6 h-6 mr-2" />{paragraph}</h2>;
            }
            if (isESPNSynopsis) {
              return <p key={idx} className="mb-8 leading-relaxed text-xl text-gray-900 font-medium italic border-l-4 border-red-500 pl-4">{paragraph}</p>;
            }
            return (
              <p key={idx} className="mb-6 leading-relaxed text-lg text-justify text-gray-700">
                {paragraph}
              </p>
            );
          })}
        </article>

        {article.originalLink && (
          <div className="mt-10 bg-gray-50 p-6 rounded-xl border border-gray-200 flex flex-col sm:flex-row items-center justify-between gap-4">
            <div className="text-gray-700 font-medium">
              Want to read the original source article for this story?
            </div>
            <a 
              href={article.originalLink} 
              target="_blank" 
              rel="noopener noreferrer"
              className="bg-red-600 hover:bg-red-700 text-white px-6 py-3 rounded-full font-bold flex items-center transition-colors whitespace-nowrap"
            >
              Read Original on ESPN
              <ExternalLink className="ml-2 h-4 w-4" />
            </a>
          </div>
        )}

        {/*
        <div className="mt-12 pt-8 border-t border-gray-200 text-center">
          <p className="text-gray-500 mb-4">Advertisement</p>
          <ins className="adsbygoogle"
               style={{display: 'block', textAlign: 'center'}}
               data-ad-layout="in-article"
               data-ad-format="fluid"
               data-ad-client="ca-pub-1766207958063879"
               data-ad-slot="auto"></ins>
        </div>
        */}
      </div>
    </div>
  );
};

export default NewsArticle;
